//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entity : DbContext
    {
        public Entity()
            : base("name=Entity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblFeed> tblFeeds { get; set; }
        public virtual DbSet<tblProfile> tblProfiles { get; set; }
        public virtual DbSet<tblRequest> tblRequests { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<vwUser_Feed> vwUser_Feed { get; set; }
        public virtual DbSet<vwUser_Profile> vwUser_Profile { get; set; }
        public virtual DbSet<vwUser_Request_Receiving> vwUser_Request_Receiving { get; set; }
        public virtual DbSet<vwUser_Request_Sending> vwUser_Request_Sending { get; set; }
        public virtual DbSet<tblLikeList> tblLikeLists { get; set; }
        public virtual DbSet<vwFeed_Like> vwFeed_Like { get; set; }
    }
}
