//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUser_Request_Sending
    {
        public int RequestID { get; set; }
        public int UserID_Sending { get; set; }
        public int UserID_Receiving { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string Username { get; set; }
        public string Pasword { get; set; }
    }
}
